// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwf1FL3WgjMLd_nbuaTABXeBQyHybKfsA',
    appId: '1:647233693575:web:2763374d549ef9e8515522',
    messagingSenderId: '647233693575',
    projectId: 'women-safety-2d77b',
    authDomain: 'women-safety-2d77b.firebaseapp.com',
    databaseURL: 'https://women-safety-2d77b-default-rtdb.firebaseio.com',
    storageBucket: 'women-safety-2d77b.appspot.com',
    measurementId: 'G-H3HT16C3ET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTaOtKDVv6249saxJgcywLuXFl4QN5zq8',
    appId: '1:647233693575:android:96a7c9b209556801515522',
    messagingSenderId: '647233693575',
    projectId: 'women-safety-2d77b',
    databaseURL: 'https://women-safety-2d77b-default-rtdb.firebaseio.com',
    storageBucket: 'women-safety-2d77b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9HNGysNHMSjtGTOamvRNuNo8y6DJRVXY',
    appId: '1:647233693575:ios:cec6c5e3db7ffe7f515522',
    messagingSenderId: '647233693575',
    projectId: 'women-safety-2d77b',
    databaseURL: 'https://women-safety-2d77b-default-rtdb.firebaseio.com',
    storageBucket: 'women-safety-2d77b.appspot.com',
    iosBundleId: 'com.example.womenss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9HNGysNHMSjtGTOamvRNuNo8y6DJRVXY',
    appId: '1:647233693575:ios:cec6c5e3db7ffe7f515522',
    messagingSenderId: '647233693575',
    projectId: 'women-safety-2d77b',
    databaseURL: 'https://women-safety-2d77b-default-rtdb.firebaseio.com',
    storageBucket: 'women-safety-2d77b.appspot.com',
    iosBundleId: 'com.example.womenss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwf1FL3WgjMLd_nbuaTABXeBQyHybKfsA',
    appId: '1:647233693575:web:f603bd2ad6dc5c2e515522',
    messagingSenderId: '647233693575',
    projectId: 'women-safety-2d77b',
    authDomain: 'women-safety-2d77b.firebaseapp.com',
    databaseURL: 'https://women-safety-2d77b-default-rtdb.firebaseio.com',
    storageBucket: 'women-safety-2d77b.appspot.com',
    measurementId: 'G-LL6L9FG6G6',
  );

}